on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.5
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (hey Left)
        run: west build -s zmk/app -b nrfmicro_13 -- -DSHIELD=hey_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: hey DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/nrfmicro_13.dts.pre.tmp
      - name: hey Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 hey_left_nrfmicro_13.uf2
      - name: Archive (hey Left)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: hey_left_nrfmicro_13.uf2
      - name: West Build (hey Right)
        run: west build --pristine -s zmk/app -b nrfmicro_13 -- -DSHIELD=hey_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: hey Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 hey_right_nrfmicro_13.uf2
      - name: Archive (hey Right)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: hey_right_nrfmicro_13.uf2
